### ISSUE TITLE
Download blank page if window size decreased

### ISSUE THREAD

**Issue by chrisdotslash** [ArthurBeaulieu/ORlyGenerator#4]
Hello! Thanks for the tool.

For some reason, if you work in a decreased-size window and hit Download, the cover you get is entirely blank. Once you resize the window to 100% of the viewport, downloading the same cover works just fine. Thought I'd let you know.

**Comment by ArthurBeaulieu** [comment]
Hello and thanks for this raised issue.
I reproduce, when viewport triggers the css media-query for mobile device.
I'll have a look on a resolution.
Kind regards
Arthur

**Comment by ArthurBeaulieu** [comment]
Issue is now fixed, it was due to html2canvas considering scrollY into account when rendering the canvas.
Feel free to reopen issue if this happens again, hopefully it won't !
Thanks again for raising it

**Comment by chrisdotslash** [comment]
That sounds great, thanks for fixing it!

I just checked and it works just fine in a reduced viewport.
